apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=        # base64 of "postgres"
  POSTGRES_PASSWORD: cGFzc3dvcmQ=    # base64 of "password"
  POSTGRES_DB: cWJpdA==              # base64 of "qbit"

  # Tip: To change username/password/db, encode them with:
  # echo -n "your_text" | base64