# .github/workflows/test.yml
name: Lint and Test

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          corepack enable
          pnpm install

      - name: Lint code
        run: pnpm lint

      # Optional test command (adjust if you add test script later)
      # - name: Run Tests
      #   run: pnpm test
